### ISSUE TITLE
Error if hierarchy child is created (Ver. 0.6.5)

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#105]
If I analyze one dataset, gate for a population with a polygon, and then create a child plot, I get to following error message:

[Window Title]
Error

[Content]
Traceback (most recent call last):
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.controls_filtering", line 300, in OnHierarchyCreateChild
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\dclab.rtdc_dataset", line 95, in __init__
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\dclab.rtdc_dataset", line 160, in _init_data_with_hierarchy
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\dclab.rtdc_dataset", line 341, in ApplyFilter
IndexError: index 901 is out of bounds for axis 1 with size 901

[OK]

**Comment by paulmueller** [comment]
I cannot reproduce this error at the time. Could you please check if this was fixed by 24b0e3e94fe06cd6032e0e39497dfc161d0edcb5?

**Comment by phidahl** [comment]
Yes, with 0.6.5dev1 it works. Thanks a lot!
