### ISSUE TITLE
Error if Batch analysis is started (Ver. 0.6.5)

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#106]
If a analyze one dataset and go to Batch/statistical analysis, I get the following error:

[Window Title]
Error

[Content]
Traceback (most recent call last):
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.frontend", line 387, in OnMenuBatchFolder
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.batch", line 125, in __init__
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.batch", line 248, in OnRadioHere
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.batch", line 278, in OnSelectMeasurement
KeyError: u'_filter_area'

[OK]

**Comment by phidahl** [comment]
This helped, noe the batch window shows up.
