### ISSUE TITLE
Batch analysis crashes for larger datasets

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#108]
Analysing a large dataset of 85 measurements with 22,000 cells each I get a memory error.
I think, if the data would be loaded processed and deleted from memory one after another it should work with any number of measurements.  The analysis of one dataset is not depending on the others, so there's no need to have them in memory at the same time.

[Window Title]
Error

[Content]
Traceback (most recent call last):
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.batch", line 158, in OnBatch
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.analysis", line 44, in __init__
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\dclab.rtdc_dataset", line 98, in __init__
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\dclab.rtdc_dataset", line 211, in _init_data_with_tdms
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\nptdms.tdms", line 169, in __init__
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\nptdms.tdms", line 194, in _read_segments
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\nptdms.tdms", line 729, in _initialise_data
MemoryError

[OK]

**Comment by paulmueller** [comment]
Batch analysis is now processing the tmds files one by one. Could you please check if this solved the problem? (7ff434b)
