### ISSUE TITLE
Cannot start shapeout in OSX (singular matrix, and other errors)

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#117]
On macOs I cannot start the current development branch.

I get the following error message:

Traceback (most recent call last):
  File "ShapeOut.py", line 63, in <module>
    main()
  File "ShapeOut.py", line 30, in main
    app = prepare_app()
  File "/Users/phi/repo_github/ShapeOut/shapeout/__main__.py", line 61, in prepare_app
    app.frame = frontend.Frame(version)
  File "/Users/phi/repo_github/ShapeOut/shapeout/gui/frontend.py", line 118, in __init__
    self.NewAnalysis([rtdc_ds])
  File "/Users/phi/repo_github/ShapeOut/shapeout/gui/frontend.py", line 322, in NewAnalysis
    self.PlotArea.Plot(anal)
  File "/Users/phi/repo_github/ShapeOut/shapeout/gui/plot_main.py", line 60, in Plot
    self.mainplot.Plot(anal)
  File "/Users/phi/repo_github/ShapeOut/shapeout/gui/plot_main.py", line 124, in Plot
    aplot = plot_scatter.scatter_plot(anal.measurements[c_plot])
  File "/Users/phi/repo_github/ShapeOut/shapeout/gui/plot_scatter.py", line 119, in scatter_plot
    set_scatter_data(scatter_plot, mm)
  File "/Users/phi/repo_github/ShapeOut/shapeout/gui/plot_scatter.py", line 268, in set_scatter_data
    density = mm.GetKDE_Scatter(yax=yax, xax=xax, positions=positions)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dclab/rtdc_dataset.py", line 817, in GetKDE_Scatter
    density = kde_fct(**kde_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dclab/cached.py", line 57, in __call__
    data = self.func(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dclab/kde_methods.py", line 42, in kde_gauss
    estimator = gaussian_kde([events_x.flatten(), events_y.flatten()])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/stats/kde.py", line 171, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/stats/kde.py", line 498, in set_bandwidth
    self._compute_covariance()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/stats/kde.py", line 509, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/linalg/basic.py", line 687, in inv
    raise LinAlgError("singular matrix")
LinAlgError: singular matrix

**Comment by paulmueller** [comment]
Thanks for testing with MacOS. I patched dclab (see above) which might have solved this issue.

**Comment by phidahl** [comment]
Thanks,
and happy new year :)
now I other errors.. Measurement explorer finds my measurements, but if I analyze one of them, I get:

Traceback (most recent call last):
  File "/Users/phi/repo_github/ShapeOut/shapeout/gui/explorer.py", line 138, in OnAnalyze
    self.external_analyze(files)
  File "/Users/phi/repo_github/ShapeOut/shapeout/gui/frontend.py", line 319, in NewAnalysis
    self.analysis._clear()
  File "/Users/phi/repo_github/ShapeOut/shapeout/analysis.py", line 75, in _clear
    for tr in list(mm.traces.keys()):
AttributeError: 'RTDC_DataSet' object has no attribute 'traces'


And some warnings in the terminal for each dataset:

warnings.warn("Non-standard directory naming scheme: {}".format(path))
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dclab/rtdc_dataset.py:964: UserWarning: Non-standard directory naming scheme: /Users/phi/WORKING/20161220_katarzyna_philipp_stable_nlsGFP_release/20161220_1517_paris_stable_nlsGFP_noco_rel_15m/M1_20161220_1517_paris_stable_nlsGFP_noco_rel_15m.tdms

**Comment by paulmueller** [comment]
Does this also only happen on MacOS?

**Comment by phidahl** [comment]
Only MacOS, yes.

**Comment by phidahl** [comment]
Now it works. I tested:
-Start shapeout
-Load a frtdc dataset
-export avi
Thank you.
