### ISSUE TITLE
FFMPEG not downloaded on virtual machine

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#165]
If I run shapout on a virtual machine, with win7 (Virtual Box), the ffmpeg extension cannot be downloaded. I get an error message and the program won't react anymore.

[Window Title]
Error

[Content]
Traceback (most recent call last):
  File "ShapeOut.py", line 66, in <module>
  File "ShapeOut.py", line 38, in main
  File "gui\frontend.py", line 175, in InitRun
  File "site-packages\imageio\plugins\ffmpeg.py", line 58, in download
  File "site-packages\imageio\core\fetching.py", line 121, in get_remote_file
  File "site-packages\imageio\core\fetching.py", line 177, in _fetch_file
IOError: Unable to download 'ffmpeg-win32-v3.2.4.exe'. Perhaps there is a no internet connection? If there is, please report this problem.

[OK]

**Comment by paulmueller** [comment]
Looks like a networking problem in imageio. I am planning to include the ffmpeg binary with ShapeOut. A workaround would be to manually install ffmpeg in the virtual machine.

**Comment by paulmueller** [comment]
Please try the latest build: https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.690

**Comment by phidahl** [comment]
That worked! There was  no error message, and I could display images of cells.
