### ISSUE TITLE
Plotting circularity with isoelastics fails

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeOut#197]
Steps to reproduce:
- Analyze a measurement
- Select Circularity instead of Deformation as the y plot axis
```
Traceback (most recent call last):
  File "shapeout/gui/controls_plotting.py", line 306, in OnApply
    self.funcparent.OnChangePlot(e)
  File "shapeout/gui/controls.py", line 226, in OnChangePlot
    self.frame.PlotArea.Plot(self.analysis)
  File "shapeout/gui/plot_main.py", line 60, in Plot
    self.mainplot.Plot(anal)
  File "shapeout/gui/plot_main.py", line 124, in Plot
    aplot = plot_scatter.scatter_plot(anal.measurements[c_plot])
  File "shapeout/gui/plot_scatter.py", line 75, in scatter_plot
    isoel = isoelastics.default.get(**kwargs)
  File "/home/paul/repos/dclab/dclab/isoelastics/__init__.py", line 214, in get
    viscosity_out=viscosity)
  File "/home/paul/repos/dclab/dclab/isoelastics/__init__.py", line 128, in convert
    raise ValueError("Columns must be one of: area_um, deform!")
ValueError: Columns must be one of: area_um, deform!
```

**Comment by paulmueller** [comment]
closed by https://github.com/ZELLMECHANIK-DRESDEN/dclab/commit/cbd55d6fe8a9b689ee0eb822b9f59b88ab8ee349
