### ISSUE TITLE
Cannot load old sessions

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#212]
[Window Title]
Error

[Content]
Traceback (most recent call last):
  File "shapeout\gui\frontend.py", line 525, in OnMenuLoad
  File "shapeout\gui\session_ui.py", line 48, in open_session
  File "shapeout\gui\session_ui.py", line 72, in open_session_worker
  File "shapeout\session\conversion.py", line 332, in compatibilitize_session
  File "shapeout\session\conversion.py", line 100, in cleanup_old_config_sections
  File "site-packages\dclab\rtdc_dataset\config.py", line 81, in __init__
  File "site-packages\dclab\rtdc_dataset\config.py", line 219, in load_from_file
ValueError: invalid literal for int() with base 10: '0.000000000000'

[OK]

Is there maybe a workaraound? change something in the session file or so?

**Comment by phidahl** [comment]
And the 0.8.4.dev5 gives me this. The data contains columns in the tdms that were added later. with the name userdef1 and userdef2

[Window Title]
Error

[Content]
Traceback (most recent call last):
  File "shapeout\gui\frontend.py", line 528, in OnMenuLoad
  File "shapeout\gui\session_ui.py", line 48, in open_session
  File "shapeout\gui\session_ui.py", line 153, in open_session_worker
  File "shapeout\session\rw.py", line 131, in load
  File "site-packages\dclab\rtdc_dataset\fmt_hierarchy.py", line 280, in apply_filter
  File "site-packages\dclab\rtdc_dataset\core.py", line 177, in apply_filter
  File "site-packages\dclab\rtdc_dataset\filter.py", line 138, in update
  File "site-packages\dclab\rtdc_dataset\fmt_hierarchy.py", line 230, in __getitem__
  File "site-packages\dclab\rtdc_dataset\core.py", line 107, in __getitem__
KeyError: u"Feature 'userdef1' does not exist!"


[OK]

**Comment by paulmueller** [comment]
I need more information. Best would be if you gave me the session file and the experimental data so I can debug this.

Did you happen to download the 0.8.4 release when it was still a pre-release on GitHub (I had to rebuild the release because of a similar error, sorry for the inconvenience)? Please check the version of dclab (Help->Software). It should be dclab 0.3.2.dev2 for ShapeOut 0.8.4. If this is not the case, please re-download 0.8.4 from GitHub and you will probably get the second error.

**Comment by phidahl** [comment]
Here is a session file and the source data. It contains the columns userdef1 and userdef2 that seem to make problems.

https://zmd.craban.de/seafile/f/c91bd015d3e04211ab70/?dl=1

**Comment by paulmueller** [comment]
I cannot reproduce this bug on Linux, but the labelling of the user defined columns in the tdms file looks wrong. In dclab, these are imported from tdms files with the key "userDefX". The present tdms file has the keys "UserDefX" (with a capital "U"). If you added the user-defined columns by hand, please try again with a lower case "u".

**Comment by phidahl** [comment]
The first error I posted only occurs for the initial release of 0.8.4

The second in newer version. Renaming the columns to userDef1 and userDef2 didn't help.

**Comment by paulmueller** [comment]
Should work with the latest version of dclab:
https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.847/job/6s8goesrtmgf7u5r

**Comment by phidahl** [comment]
It works.
