### ISSUE TITLE
Crash on filtering

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#73]
If a set a filter for FL-3max channel to Min: 1000, Max: 33000, I get the following error message:

Traceback (most recent call last):
  File "/Users/phi/repo_git_shapeout_develop/ShapeOut/shapeout/gui/controls.py", line 151, in OnChangeFilter
    self.analysis.SetParameters(cfg)
  File "/Users/phi/repo_git_shapeout_develop/ShapeOut/shapeout/tlabwrap.py", line 459, in SetParameters
    if (newcfg["Plotting"]["Scale X"] == "Log" or
KeyError: 'Plotting'

**Comment by paulmueller** [comment]
I fixed the bug in develop. I kept version 0.5.9 as pre-release because of this bug. Seems like the software is not usable as-is.
