### ISSUE TITLE
Session Loading with Child Plots fails

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#99]
I get an error if I do the following:

Create one plot
do some polygon filter
create a child plot
save the session
close and reopen shapeout
load the saved session

The error is:

[Window Title]
Error

[Content]
Traceback (most recent call last):
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.frontend", line 528, in OnMenuLoad
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.frontend", line 272, in NewAnalysis
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.analysis", line 50, in __init__
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.analysis", line 113, in _ImportDumped
AttributeError: 'NoneType' object has no attribute 'title'

Cheers,
Philipp

**Comment by paulmueller** [comment]
I could not reproduce this bug, but I guess I have found the cause already (see commit above). If the problem persists, please send me the data files.

**Comment by phidahl** [comment]
I tested 0.6.4.dev3. It loads session files with children sucessfully.
Thanks!
